{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.11",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.5.jar",
          "url": "panel-lib-mc1.21.11-0.1.5.jar",
          "size": 8050927,
          "sha512": "082d25043d6c91d20f21078669bf738cbc1faf7bb58bb66ff707087116d209533f840d95ec3c38d4b59f5ce3b8af9c62772371111a8fba0b7bcd257339005c95",
          "sha256": "7182817ad48acf864cba002bc081ab2264f094c6039980f721e8535c253979ca",
          "sha1": "9c561a9c27e95003ab5fe8265bb7a641ffce063f",
          "md5": "b5f9c265bc930a0f1704274b0b1868f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.5.jar",
          "url": "panel-lib-mc1.21.11-0.1.5.jar",
          "size": 8050927,
          "sha512": "082d25043d6c91d20f21078669bf738cbc1faf7bb58bb66ff707087116d209533f840d95ec3c38d4b59f5ce3b8af9c62772371111a8fba0b7bcd257339005c95",
          "sha256": "7182817ad48acf864cba002bc081ab2264f094c6039980f721e8535c253979ca",
          "sha1": "9c561a9c27e95003ab5fe8265bb7a641ffce063f",
          "md5": "b5f9c265bc930a0f1704274b0b1868f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.5-sources.jar",
          "url": "panel-lib-mc1.21.11-0.1.5-sources.jar",
          "size": 634755,
          "sha512": "afe0cfc5cafa7f9f3dc8032dadc640d7007b6baa176821e1b58e8941d1f5a9fc10c6e7f5bec33db8a881939bf41a51ee09602f0c217cdbf4de0bcc47ece8fbe1",
          "sha256": "4daf022fa9cc3065eff91096f4604552ba2941c2b2d6f9f0b925f419b3cb9773",
          "sha1": "6c3dca5a065cb7a827234afe7813db6cdbcfe447",
          "md5": "824b66d137183a8b845e4579e2be31b3"
        }
      ]
    }
  ]
}
