{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc26.1",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc26.1-0.1.3.jar",
          "url": "panel-lib-mc26.1-0.1.3.jar",
          "size": 8037446,
          "sha512": "5a696d46ed1130ea54e07ce604aa25416a41e78dcc55be8f53e494e3ddf8183bafc860966fc8a37f03d99f7aae0faf90a85d025f74cad6b7bf07a4b3f58fbaac",
          "sha256": "4dcad8b14739e0d19bdf3469c7afbc0506205bc82720d6d26b3b228d832cf44c",
          "sha1": "01e381573a2c35905c049158ebe0e84c57793f77",
          "md5": "4defd4a1950c6e1c1023e5f40e20c044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.151.0+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc26.1-0.1.3.jar",
          "url": "panel-lib-mc26.1-0.1.3.jar",
          "size": 8037446,
          "sha512": "5a696d46ed1130ea54e07ce604aa25416a41e78dcc55be8f53e494e3ddf8183bafc860966fc8a37f03d99f7aae0faf90a85d025f74cad6b7bf07a4b3f58fbaac",
          "sha256": "4dcad8b14739e0d19bdf3469c7afbc0506205bc82720d6d26b3b228d832cf44c",
          "sha1": "01e381573a2c35905c049158ebe0e84c57793f77",
          "md5": "4defd4a1950c6e1c1023e5f40e20c044"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc26.1-0.1.3-sources.jar",
          "url": "panel-lib-mc26.1-0.1.3-sources.jar",
          "size": 627730,
          "sha512": "a9593c0126a91c14bca7e1ee7fefd211aa54aaa18c40ab366ac7ee258e5a25912930ffd3372addf2e7ff394562a93d57c26db0573ff116ee587414bbc5c63907",
          "sha256": "c7eb28f9a51f8ff2464d443cc7aeacb8ae3241d92f46323adf294de46743fd5e",
          "sha1": "1378faf0386306be72e2b6d31fd74ace434d12e0",
          "md5": "7adc1ca2d67fab68fc2f5278ddf283c2"
        }
      ]
    }
  ]
}
