{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.10",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.10-0.1.4.jar",
          "url": "panel-lib-mc1.21.10-0.1.4.jar",
          "size": 8049382,
          "sha512": "367b77500b0df2becdc47eeb81ecb94a21f9a73d7f36085aca9b96a98a77c8bd375b7e8fb96d1fa431180e04ca888c5b44e86d9d2b2510ce0471cf5d3023156e",
          "sha256": "29bf49e5e785c03a546ca57d38dfdc1c096ef5c45570b49199064dbd36efdbfb",
          "sha1": "3e6a47add6e150678c21f705f9c5f94673eb2b16",
          "md5": "3f06847dbcfea19eed238bc29bebf69b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.4+1.21.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.10-0.1.4.jar",
          "url": "panel-lib-mc1.21.10-0.1.4.jar",
          "size": 8049382,
          "sha512": "367b77500b0df2becdc47eeb81ecb94a21f9a73d7f36085aca9b96a98a77c8bd375b7e8fb96d1fa431180e04ca888c5b44e86d9d2b2510ce0471cf5d3023156e",
          "sha256": "29bf49e5e785c03a546ca57d38dfdc1c096ef5c45570b49199064dbd36efdbfb",
          "sha1": "3e6a47add6e150678c21f705f9c5f94673eb2b16",
          "md5": "3f06847dbcfea19eed238bc29bebf69b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.10-0.1.4-sources.jar",
          "url": "panel-lib-mc1.21.10-0.1.4-sources.jar",
          "size": 634317,
          "sha512": "3e81f711f84d197c3a7c548b210910c801483fc1a72569defc945d024f9ef7a1ec0a079104996095a5104e4cb1b2bd02e5f44d92fc4817a09e7676681378037d",
          "sha256": "53bd12851d800253e18111548a87aa998a2defd97d74ad5ef40ec0981424297d",
          "sha1": "24072a1ad9fe605443f871666a2ca68d76892cb1",
          "md5": "b7a6d22cb946a8f73858029fd8b9fd84"
        }
      ]
    }
  ]
}
