{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.9",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.9-0.1.3.jar",
          "url": "panel-lib-mc1.21.9-0.1.3.jar",
          "size": 8044170,
          "sha512": "6a92901b23c13ec1a09b905fad9ed4f96333f069ce5b74bcaf116b891d0e5b5d904c4d6a2b497f89a8e48755308d0e978140e252b0865f44b3186bd153d70f56",
          "sha256": "f2d83d156f75d9ef41364c14921e88d11f747df0d005c52a0034b1e491921b48",
          "sha1": "17f862b50886b185ff16d6cc63e7fd1183b04ba3",
          "md5": "709d4b598bba8f5381a479a453eb448c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.1+1.21.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.9-0.1.3.jar",
          "url": "panel-lib-mc1.21.9-0.1.3.jar",
          "size": 8044170,
          "sha512": "6a92901b23c13ec1a09b905fad9ed4f96333f069ce5b74bcaf116b891d0e5b5d904c4d6a2b497f89a8e48755308d0e978140e252b0865f44b3186bd153d70f56",
          "sha256": "f2d83d156f75d9ef41364c14921e88d11f747df0d005c52a0034b1e491921b48",
          "sha1": "17f862b50886b185ff16d6cc63e7fd1183b04ba3",
          "md5": "709d4b598bba8f5381a479a453eb448c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.9-0.1.3-sources.jar",
          "url": "panel-lib-mc1.21.9-0.1.3-sources.jar",
          "size": 629137,
          "sha512": "e06356a5aba397ff2d67cc331c66387acf0fc7dfbefc51cafbc7be5a245dc9642c2391497dea47b715a4dd34cbdd9f74e61ae79f01fdc70317e55f053b5618df",
          "sha256": "e82c8bed63da18aa5ad8cc55ab0549b9d6200f47b31b20fd301eb1b68dcfb0d8",
          "sha1": "ab5ba6347585b2d567c50de60e5c8df651826cbf",
          "md5": "3c24371a245eda6f885f264ebca4b04d"
        }
      ]
    }
  ]
}
