{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.11",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.3.jar",
          "url": "panel-lib-mc1.21.11-0.1.3.jar",
          "size": 8044403,
          "sha512": "3915d221171fb5d991d29b257bca01c231b37f1d182d70e512d1468244335d1a4102e030ada8f63812d0fa599cca369a5b91d25ef9ad9f6d5fd60b226f0a3d9c",
          "sha256": "1924cebcea81147675d0b93b318d9033c6613218624056c76ce1be24ccda4546",
          "sha1": "886170ac15a8898dffa5a24d8717f6db0dcad958",
          "md5": "5805eca0ef86c5d53040a476c2d01981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.3.jar",
          "url": "panel-lib-mc1.21.11-0.1.3.jar",
          "size": 8044403,
          "sha512": "3915d221171fb5d991d29b257bca01c231b37f1d182d70e512d1468244335d1a4102e030ada8f63812d0fa599cca369a5b91d25ef9ad9f6d5fd60b226f0a3d9c",
          "sha256": "1924cebcea81147675d0b93b318d9033c6613218624056c76ce1be24ccda4546",
          "sha1": "886170ac15a8898dffa5a24d8717f6db0dcad958",
          "md5": "5805eca0ef86c5d53040a476c2d01981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.11-0.1.3-sources.jar",
          "url": "panel-lib-mc1.21.11-0.1.3-sources.jar",
          "size": 629135,
          "sha512": "70c83fe50cb566d28fe608fbe05187b94dfd351fd83d7486ee5fb5ef70e647f596093e265e026c17cabc3089539ba6d0b515a8faa130f40fe68ee2ff49fd33a4",
          "sha256": "552624aca0d93c16e0584e2c239a265f3437baaf69f7440c52741dff0f3992c2",
          "sha1": "507c58de87c861162109559c3bc307181d0f33e2",
          "md5": "65ba95ad57296a5d99a3a7c601bdc472"
        }
      ]
    }
  ]
}
