{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.8",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.3.jar",
          "url": "panel-lib-mc1.21.8-0.1.3.jar",
          "size": 8043900,
          "sha512": "24acba402594ce7b62b4775f9c21823277b372071554a7f2d2aa5c4b587235d62ab14a146c906b710e7d9ad183df467c1756f62d14288ce1b89c4d67c72f74cc",
          "sha256": "29cc09ea5ffac6f875983315092c26542cf32f01e585591e23fb7ed03678ed10",
          "sha1": "dc0ad9e2472312f7020473bf224a2b9ff81f1f80",
          "md5": "726249baeb016c3f42f85ecef4ce9e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.136.1+1.21.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.3.jar",
          "url": "panel-lib-mc1.21.8-0.1.3.jar",
          "size": 8043900,
          "sha512": "24acba402594ce7b62b4775f9c21823277b372071554a7f2d2aa5c4b587235d62ab14a146c906b710e7d9ad183df467c1756f62d14288ce1b89c4d67c72f74cc",
          "sha256": "29cc09ea5ffac6f875983315092c26542cf32f01e585591e23fb7ed03678ed10",
          "sha1": "dc0ad9e2472312f7020473bf224a2b9ff81f1f80",
          "md5": "726249baeb016c3f42f85ecef4ce9e79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.3-sources.jar",
          "url": "panel-lib-mc1.21.8-0.1.3-sources.jar",
          "size": 629177,
          "sha512": "b11aaf0ea7aab1cd8adba739b21b2aaf76bf718097e07965b18f854d61ea9e1c2d2a951a40b128563d6087de1fd6c2f8aa10939d45072654a2b846a0a0a398b7",
          "sha256": "57697c160c848ffc14bab5e70d5ab66daa003343e47e8f37c2064631618ccf81",
          "sha1": "6bcc8893533342bc5b9dbeea31c4d53393775af0",
          "md5": "2762cbb5156b41a166e29c54ef92a8d3"
        }
      ]
    }
  ]
}
