{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.harrison",
    "module": "panel-lib-mc1.21.8",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.4.jar",
          "url": "panel-lib-mc1.21.8-0.1.4.jar",
          "size": 8049092,
          "sha512": "a97bd545dbe816f7650928aad9000d21495e3314ccad4f8955768c4b866cd7b4042f1c2bf01798a186a108296c3253f734d0de4415549576bc044f598e5e7560",
          "sha256": "838f07845615ff8e30f7e30a6eb5fc8f56096b03b4d08de0efb8ea9bad776413",
          "sha1": "d9988c9e9bdae505ecd68f7bd6a5cf0e04b65d69",
          "md5": "0619e7701edfc74decc488641de0fc58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.89.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.89.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.136.1+1.21.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.12+kotlin.2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.4.jar",
          "url": "panel-lib-mc1.21.8-0.1.4.jar",
          "size": 8049092,
          "sha512": "a97bd545dbe816f7650928aad9000d21495e3314ccad4f8955768c4b866cd7b4042f1c2bf01798a186a108296c3253f734d0de4415549576bc044f598e5e7560",
          "sha256": "838f07845615ff8e30f7e30a6eb5fc8f56096b03b4d08de0efb8ea9bad776413",
          "sha1": "d9988c9e9bdae505ecd68f7bd6a5cf0e04b65d69",
          "md5": "0619e7701edfc74decc488641de0fc58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "panel-lib-mc1.21.8-0.1.4-sources.jar",
          "url": "panel-lib-mc1.21.8-0.1.4-sources.jar",
          "size": 634357,
          "sha512": "26daff91cb301ec5fcb057c02304788c7fb3db70b3b05b1ab2d66ccac170f021cf82fd0ab8d5d7481a97975afdb0c6f9b47a3fb5c58a1203cce53e7feaeaddcb",
          "sha256": "a2dcf822dcaf2e171745dd45cd45678380b2820a4422ec2473e7823422a883d2",
          "sha1": "7bc607f0a2625a59d2d9fdc74decceccd0d85b63",
          "md5": "196b137700cb0dc456140d9a4f4ce54b"
        }
      ]
    }
  ]
}
